# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
# Edge detection
# kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

# Sharpen
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  3., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[5, 2, 7, 2, 7, 8, 8, 3, 1, 7, 5, 7],
       [2, 4, 2, 9, 8, 1, 1, 9, 5, 8, 6, 6],
       [6, 0, 2, 2, 8, 0, 2, 7, 1, 2, 2, 4],
       [9, 9, 4, 0, 4, 5, 2, 1, 0, 9, 7, 2],
       [2, 1, 0, 0, 7, 4, 1, 9, 9, 4, 3, 2],
       [2, 3, 7, 6, 7, 1, 8, 2, 1, 3, 9, 7],
       [0, 5, 7, 9, 8, 4, 1, 0, 3, 5, 2, 2],
       [3, 5, 0, 3, 9, 9, 5, 0, 4, 2, 6, 9],
       [6, 0, 4, 0, 7, 1, 1, 2, 9, 0, 8, 3],
       [2, 0, 2, 2, 4, 0, 7, 6, 1, 4, 9, 2],
       [5, 5, 6, 3, 1, 3, 7, 8, 1, 7, 8, 2],
       [5, 3, 9, 6, 4, 8, 8, 6, 3, 8, 6, 6]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int8)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[5, 2, 7, 2, 7, 8, 8, 3, 1, 7, 5, 7],
       [2, 4, 2, 9, 8, 1, 1, 9, 5, 8, 6, 6],
       [6, 0, 2, 2, 8, 0, 2, 7, 1, 2, 2, 4],
       [9, 9, 4, 0, 4, 5, 2, 1, 0, 9, 7, 2],
       [2, 1, 0, 0, 7, 4, 1, 9, 9, 4, 3, 2],
       [2, 3, 7, 6, 7, 1, 8, 2, 1, 3, 9, 7],
       [0, 5, 7, 9, 8, 4, 1, 0, 3, 5, 2, 2],
       [3, 5, 0, 3, 9, 9, 5, 0, 4, 2, 6, 9],
       [6, 0, 4, 0, 7, 1, 1, 2, 9, 0, 8, 3],
       [2, 0, 2, 2, 4, 0, 7, 6, 1, 4, 9, 2],
       [5, 5, 6, 3, 1, 3, 7, 8, 1, 7, 8, 2],
       [5, 3, 9, 6, 4, 8, 8, 6, 3, 8, 6, 6]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   6, -16,  13,  -1, -14, -17,  11,  -4,   4,  -3,   0],
       [  0, -21,  -2, -13,  10, -16,  -4,   8, -11, -14, -13,   0],
       [  0,  13,   1, -10,  -8,   5,  -3, -15, -20,  14,   5,   0],
       [  0, -11, -12, -13,   6,  -2, -20,  14,  13, -12, -13,   0],
       [  0,  -6,   5,  -5,  -1, -20,  19, -12, -14, -10,  12,   0],
       [  0,   0,   0,   3,  -5,  -7, -14,  -6,  -1,   5, -16,   0],
       [  0,   7, -19,  -9,   0,   8,   4, -11,  -2,  -9,  -3,   0],
       [  0, -15,  10, -16,   7, -14, -12, -10,  20, -23,   6,   0],
       [  0,  -9,  -6,  -3,   2, -15,   7,   0, -17,  -5,   5,   0],
       [  0,   1,  -1,  -6, -11,  -7,  -5,   4, -16,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
      dtype=int8)

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()