# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
# Edge detection
# kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

# Sharpen
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  5., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[4, 5, 5, 1, 8, 2, 1, 5, 4, 7, 6, 9],
       [6, 0, 2, 3, 7, 1, 4, 3, 2, 6, 1, 0],
       [1, 3, 1, 8, 5, 4, 9, 5, 5, 8, 6, 9],
       [1, 7, 6, 9, 9, 4, 0, 2, 7, 6, 0, 4],
       [0, 7, 9, 3, 1, 4, 2, 1, 2, 6, 5, 8],
       [6, 9, 5, 8, 3, 0, 7, 5, 9, 7, 6, 7],
       [1, 1, 6, 8, 2, 0, 8, 8, 3, 1, 1, 0],
       [1, 5, 2, 8, 6, 4, 4, 1, 6, 2, 2, 6],
       [1, 0, 6, 8, 3, 5, 8, 2, 0, 5, 1, 2],
       [5, 3, 8, 0, 3, 1, 8, 7, 4, 8, 7, 0],
       [1, 2, 5, 1, 3, 8, 2, 6, 3, 6, 8, 1],
       [1, 9, 5, 0, 8, 1, 4, 2, 6, 2, 1, 3]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int8)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[4, 5, 5, 1, 8, 2, 1, 5, 4, 7, 6, 9],
       [6, 0, 2, 3, 7, 1, 4, 3, 2, 6, 1, 0],
       [1, 3, 1, 8, 5, 4, 9, 5, 5, 8, 6, 9],
       [1, 7, 6, 9, 9, 4, 0, 2, 7, 6, 0, 4],
       [0, 7, 9, 3, 1, 4, 2, 1, 2, 6, 5, 8],
       [6, 9, 5, 8, 3, 0, 7, 5, 9, 7, 6, 7],
       [1, 1, 6, 8, 2, 0, 8, 8, 3, 1, 1, 0],
       [1, 5, 2, 8, 6, 4, 4, 1, 6, 2, 2, 6],
       [1, 0, 6, 8, 3, 5, 8, 2, 0, 5, 1, 2],
       [5, 3, 8, 0, 3, 1, 8, 7, 4, 8, 7, 0],
       [1, 2, 5, 1, 3, 8, 2, 6, 3, 6, 8, 1],
       [1, 9, 5, 0, 8, 1, 4, 2, 6, 2, 1, 3]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -16,   1,  -3,  18, -12,   6,  -1,  -8,  12, -13,   0],
       [  0,   6, -14,  22,  -3,   1,  32,   6,   3,  17,  12,   0],
       [  0,  18,   4,  19,  26,   3, -17,  -3,  20,   9, -21,   0],
       [  0,  10,  24, -12, -14,  13,  -2,  -6, -13,  10,   5,   0],
       [  0,  26,  -7,  21,   4, -14,  20,   0,  28,  13,  10,   0],
       [  0, -16,  14,  16,  -7, -14,  21,  23,  -9,  -8,  -4,   0],
       [  0,  21, -15,  16,  13,   5,  -1, -15,  24,  -4,   0,   0],
       [  0, -15,  12,  23,  -7,   9,  21,  -6, -17,  14, -11,   0],
       [  0,   0,  26, -20,   8, -19,  22,  15,   2,  18,  18,   0],
       [  0,  -8,   9,  -3,  -5,  33, -16,  16,  -7,   9,  25,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
      dtype=int8)

In [13]:
# 윈도우
img = cv2.imread('D:\GitHub\ComputerVision20212\SampleFiles\lena.png', 0)


In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()